# numpy (numerical python)

In [1]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [4]:
arr=np.array((1,2,3,4))
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


# dimensions in array

In [5]:
# 1d
arr=np.array([1,2,3,4])
print(arr)
print(arr.ndim)

[1 2 3 4]
1


In [8]:
#2d array
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [9]:
# 3d
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [10]:
arr=np.array([1,2,3,4])
print(arr[0])

1


In [12]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr[0,1])
print(arr[0,0]+arr[1,1])

2
6


In [13]:
arr=np.array([[[1,2,3],[4,5,6]],
              [[7,8,9],[10,11,12]]])
print(arr[0,1,1])

5


In [15]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[1:5:2])

[2 4]


In [20]:
import numpy as np
a=np.array([[10,20,30,40],[60,70,80,90]])
print(a[0,0:3])

[10 20 30]


In [47]:
import numpy as np
a=np.array([
    [[1,2,3,4],[5,6,7,7]],
    [[5,6,7,8],[4,3,2,1]]
])
print(a[0,0,0:4])
print(a[1,0,0])
print(a.shape)

[1 2 3 4]
5
(2, 2, 4)


# checkig the data type of an array

In [23]:
arr=np.array([1,2,3,4])
print(arr.dtype)

int64


In [26]:
arr=np.array([1,2,3],dtype='S')
print(arr)

[b'1' b'2' b'3']


In [27]:
#numpy array shapea
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)



(2, 3)


In [31]:
# joining arrays
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [48]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[0,9,8],[6,5,4]])
arr=np.concatenate((arr1,arr2) ,axis=1)
arr3=np.concatenate((arr1,arr2),axis=0)
print(arr)
print(arr3)

[[1 2 3 0 9 8]
 [4 5 6 6 5 4]]
[[1 2 3]
 [4 5 6]
 [0 9 8]
 [6 5 4]]


In [38]:
# ravela nand flater
#converting multiple d array in 1d array

m=np.array([
    [[1,2,3],[4,5,6]],
    [[5,6,7],[8,7,6]]
])
print(m)
n=m.ravel()
print(n)
print(n.ndim)

[[[1 2 3]
  [4 5 6]]

 [[5 6 7]
  [8 7 6]]]
[1 2 3 4 5 6 5 6 7 8 7 6]
1


In [50]:
#unique function
k=np.array([12,1,2,1,3,4,5,5,56,6,6,7,8,9,9,1,1,1])
m=np.unique(k)
print(m)

[ 1  2  3  4  5  6  7  8  9 12 56]


In [41]:
#delete
a=np.array([12,13,14])
d=np.delete(a,[1])
print(d)

[12 14]


In [43]:
x=np.array([[1,2,3],[4,5,6]])
d=np.delete(x,[1,1])
print(d)

[1 3 4 5 6]
